version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongo-test
    ports:
      - '27017:27017'
    networks:
      - my-network
  notes:
    image: notes
    restart: always
    container_name: notes-test
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-test:27017/notes
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge